<?php require 'includes/auth.php'; require_admin(); include 'config/db.php'; include 'includes/layout.php'; include 'includes/log_func.php';
$msg='';
if(isset($_POST['update_door'])){
  $id=(int)$_POST['id']; $name=trim($_POST['door_name']); $loc=trim($_POST['location']); $status=$_POST['status'];
  $stmt=$conn->prepare('UPDATE doors SET door_name=?, location=?, status=? WHERE id=?'); $stmt->bind_param('sssi',$name,$loc,$status,$id);
  if($stmt->execute()){
    $admin=['id'=>$_SESSION['user_id'],'full_name'=>$_SESSION['full_name'],'role'=>$_SESSION['role']];
    create_log($conn,'ADMIN-PANEL',$id,$admin,'ADMIN_UPDATE_DOOR','WEB','INFO','LOW','Admin updated door status/configuration to '.$status,$_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',json_encode($_POST));
    $msg='<div class="alert alert-success">Door updated. Dashboard will show new status.</div>';
  }
}
if(isset($_POST['quick_status'])){
  $id=(int)$_POST['door_id']; $status=$_POST['quick_status'];
  $stmt=$conn->prepare('UPDATE doors SET status=? WHERE id=?'); $stmt->bind_param('si',$status,$id); $stmt->execute();
  $admin=['id'=>$_SESSION['user_id'],'full_name'=>$_SESSION['full_name'],'role'=>$_SESSION['role']];
  create_log($conn,'ADMIN-PANEL',$id,$admin,'DOOR_'.$status,'WEB','INFO','LOW','Admin manually changed door status to '.$status,$_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',json_encode($_POST));
  $msg='<div class="alert alert-success">Door status changed to '.$status.'.</div>';
}
if(isset($_POST['add_rule'])){ $stmt=$conn->prepare('INSERT INTO access_rules(door_id,role,allowed_start,allowed_end,is_enabled) VALUES(?,?,?,?,1)'); $stmt->bind_param('isss',$_POST['door_id'],$_POST['role'],$_POST['allowed_start'],$_POST['allowed_end']); $stmt->execute(); $msg='<div class="alert alert-success">Access rule added.</div>'; }
if(isset($_POST['update_rule'])){ $rid=(int)$_POST['rule_id']; $role=$_POST['role']; $start=$_POST['allowed_start']; $end=$_POST['allowed_end']; $enabled=isset($_POST['is_enabled'])?1:0; $stmt=$conn->prepare('UPDATE access_rules SET role=?, allowed_start=?, allowed_end=?, is_enabled=? WHERE id=?'); $stmt->bind_param('sssii',$role,$start,$end,$enabled,$rid); $stmt->execute(); $msg='<div class="alert alert-success">Access rule updated.</div>'; }
if(isset($_POST['delete_rule'])){ $rid=(int)$_POST['rule_id']; $conn->query("DELETE FROM access_rules WHERE id=$rid"); $msg='<div class="alert alert-warning">Access rule deleted.</div>'; }
$doorsForAdd=$conn->query('SELECT * FROM doors ORDER BY id'); $doors=$conn->query('SELECT * FROM doors ORDER BY id'); $rules=$conn->query('SELECT r.*, d.door_name, d.door_code FROM access_rules r JOIN doors d ON d.id=r.door_id ORDER BY d.door_name,r.role'); header_html('Admin Doors'); ?>
<h2>Admin Page: Door Control & Access Rules</h2><p class="small-muted">Control locked/unlocked door status and decide which role can access which door and during what time.</p><?=$msg?>
<div class="row g-3 mb-4"><div class="col-md-12"><div class="card p-3"><h5>Door Status Control</h5><table class="table table-sm"><tr><th>Code</th><th>Door Name</th><th>Location</th><th>Status</th><th>Quick Control</th><th>Save Details</th></tr><?php while($d=$doors->fetch_assoc()): ?><tr><form method="post"><td><?=h($d['door_code'])?><input type="hidden" name="id" value="<?=$d['id']?>"><input type="hidden" name="door_id" value="<?=$d['id']?>"></td><td><input class="form-control form-control-sm" name="door_name" value="<?=h($d['door_name'])?>"></td><td><input class="form-control form-control-sm" name="location" value="<?=h($d['location'])?>"></td><td><select class="form-select form-select-sm" name="status"><?php foreach(['LOCKED','UNLOCKED','OFFLINE'] as $s): ?><option <?=$d['status']==$s?'selected':''?>><?=$s?></option><?php endforeach; ?></select></td><td><button class="btn btn-sm btn-outline-secondary" name="quick_status" value="LOCKED">Lock</button> <button class="btn btn-sm btn-outline-success" name="quick_status" value="UNLOCKED">Unlock</button> <button class="btn btn-sm btn-outline-warning" name="quick_status" value="OFFLINE">Offline</button></td><td><button class="btn btn-primary btn-sm" name="update_door">Save</button></td></form></tr><?php endwhile; ?></table></div></div></div>
<div class="row g-3"><div class="col-md-4"><div class="card p-3"><h5>Add Access Rule</h5><form method="post"><label>Door</label><select class="form-select mb-2" name="door_id"><?php while($d=$doorsForAdd->fetch_assoc()): ?><option value="<?=$d['id']?>"><?=h($d['door_code'].' - '.$d['door_name'])?></option><?php endwhile; ?></select><label>Allowed Role</label><select class="form-select mb-2" name="role"><option>admin</option><option>analyst</option><option>staff</option><option>cleaner</option></select><label>Start Time</label><input class="form-control mb-2" type="time" name="allowed_start" required><label>End Time</label><input class="form-control mb-2" type="time" name="allowed_end" required><button class="btn btn-primary" name="add_rule">Add Rule</button></form></div></div><div class="col-md-8"><div class="card p-3"><h5>Current Rules</h5><table class="table table-sm"><tr><th>Door</th><th>Role</th><th>Start</th><th>End</th><th>Enabled</th><th>Action</th></tr><?php while($r=$rules->fetch_assoc()): ?><tr><form method="post"><td><?=h($r['door_code'].' - '.$r['door_name'])?><input type="hidden" name="rule_id" value="<?=$r['id']?>"></td><td><select class="form-select form-select-sm" name="role"><?php foreach(['admin','analyst','staff','cleaner'] as $role): ?><option <?=$r['role']==$role?'selected':''?>><?=$role?></option><?php endforeach; ?></select></td><td><input class="form-control form-control-sm" type="time" name="allowed_start" value="<?=h($r['allowed_start'])?>"></td><td><input class="form-control form-control-sm" type="time" name="allowed_end" value="<?=h($r['allowed_end'])?>"></td><td><input type="checkbox" name="is_enabled" <?=$r['is_enabled']?'checked':''?>></td><td><button class="btn btn-primary btn-sm" name="update_rule">Save</button> <button class="btn btn-danger btn-sm" name="delete_rule" onclick="return confirm('Delete this rule?')">Delete</button></td></form></tr><?php endwhile; ?></table></div></div></div>
<?php footer_html(); ?>
