<?php require 'includes/auth.php'; require_login(); include 'config/db.php'; include 'includes/layout.php'; include 'includes/status_helper.php';
$where=[]; if(!empty($_GET['q'])){ $q=$conn->real_escape_string($_GET['q']); $where[]="(actor_name LIKE '%$q%' OR event_type LIKE '%$q%' OR device_id LIKE '%$q%' OR reason LIKE '%$q%')"; }
if(!empty($_GET['severity'])){ $s=$conn->real_escape_string($_GET['severity']); $where[]="severity='$s'"; }
$sql='SELECT l.*, d.door_name FROM event_logs l LEFT JOIN doors d ON d.id=l.door_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY l.event_time DESC LIMIT 200';
$res=$conn->query($sql); header_html('Logs'); ?>
<h2>Forensic Logs</h2><p class="small-muted">Designed to answer: which device, who, what happened, when, where/source, and why.</p><div class="mb-3 no-print"><a class="btn btn-success" href="report.php">Generate Report / Print</a></div>
<form class="row g-2 mb-3"><div class="col-md-5"><input class="form-control" name="q" placeholder="Search device, user, event, reason" value="<?=h($_GET['q'] ?? '')?>"></div><div class="col-md-3"><select class="form-select" name="severity"><option value="">All severity</option><?php foreach(['LOW','MEDIUM','HIGH','CRITICAL'] as $s): ?><option <?=($_GET['severity']??'')==$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary">Filter</button></div></form>
<div class="alert alert-light border"><b>Status color guide:</b> <span class="status-badge status-success">GRANTED/SUCCESS</span> <span class="status-badge status-failed">DENIED/FAILED</span> <span class="status-badge status-warning">WARNING/TAMPERED</span></div>
<div class="card p-3"><table class="table table-hover table-sm"><tr><th>When</th><th>Which Device</th><th>Who</th><th>What</th><th>Event Status</th><th>Severity</th><th>Why / How</th><th>Hash</th></tr><?php while($r=$res->fetch_assoc()): ?><tr class="<?=row_class($r['result'],$r['event_type'],$r['integrity_status'])?>"><td><?=h($r['event_time'])?></td><td><?=h($r['device_id'].' '.$r['door_name'])?></td><td><?=h($r['actor_name'].' ('.$r['actor_role'].')')?></td><td><?=h($r['event_type'])?></td><td><?=status_badge($r['result'],$r['event_type'],$r['integrity_status'])?></td><td><span class="badge badge-sev-<?=h($r['severity'])?>"><?=h($r['severity'])?></span></td><td><?=h($r['reason'])?><br><span class="small-muted">IP: <?=h($r['source_ip'])?> | Method: <?=h($r['auth_method'])?></span></td><td class="hash"><?=h($r['stored_hash'])?></td></tr><?php endwhile; ?></table></div>
<?php footer_html(); ?>
